bind-key Up    select-pane -U
bind-key Down  select-pane -D
bind-key Left  select-pane -L
bind-key Right select-pane -R

set-window-option -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# fix colours
set -g default-terminal "tmux-256color"

# plugin manager
set -g @plugin 'tmux-plugins/tpm'

# theme

set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "#458588"
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-indicator-str " tmux  "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "top"

# Enables or disables the left and right status bar
set -g @minimal-tmux-right true
set -g @minimal-tmux-left true

# expanded icon (fullscreen icon)
set -g @minimal-tmux-expanded-icon "󰘖 "

# on all tabs (default is false)
# false will make it visible for the current tab only
set -g @minimal-tmux-show-expanded-icons-for-all-tabs true

# To add or remove extra text in status bar
set -g @minimal-tmux-status-right-extra ""
set -g @minimal-tmux-status-left-extra ""

# To make the selection box rounded () or edged <>
# Default is nothing, when set to true default is edged
set -g @minimal-tmux-use-arrow false

# Not recommended to change these values
set -g @minimal-tmux-status-right "-- #S --"
# set -g @minimal-tmux-status-left "refer to code"
# set -g @minimal-tmux-status-left "--  --"

# If getting strings cut in left status or right
# Here 20 is the length of the characters in the string
# set -g status-right-length 20
# set -g status-left-length 20

#################
# DO NOT REMOVE!! 
run '~/.tmux/plugins/tpm/tpm'
